openapi: 3.1.0
info:
  title: Ping API
  version: 1.0.0
  description: API pour tester la connectiviter
servers:
  - url: 'http://localhost:8080'
paths:
  /ping:
    get:
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: pong