openapi: 3.1.0
info:
  title: User Management API
  version: 1.0.0
  description: API pour la gestion des utilisateurs
servers:
  - url: 'http://localhost:8080'
paths:
  /users:
    get:
      summary: Récupère la liste des utilisateurs
      parameters:
        - name: page
          in: query
          description: Numéro de page
          required: false
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: Taille de la page
          required: false
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
              example:
                error: Bad types for provided query parameters

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email