openapi: 3.1.0
info:
  title: Task Management API
  version: 1.0.0
  description: API pour la gestion des tâches
servers:
  - url: 'http://localhost:8080'
paths:
  /tasks:
    get:
      summary: Récupère toutes les tâches
      responses:
        '200':
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: Faire les courses
                  completed: false
                - id: 2
                  title: Réviser pour l'examen
                  completed: true
    post:
      summary: Crée de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Tâches créées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      summary: Supprime plusieurs tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              example: [1, 2, 3]
      responses:
        '200':
          description: Tâches supprimées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Récupère une tâche par son ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
              example:
                error: Task not found
    delete:
      summary: Supprime une tâche par son ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tâche supprimée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed
    TaskCreate:
      type: object
      properties:
        title:
          type: string
        completed:
          type: boolean
          default: false
      required:
        - title